name: bex
author: João Furtado
description: Web UI app for SAP BW
dependencies:
  browser: any
  datepicker: any
  html5_dnd: any
  jsonp_request: any
  sharepointauth:
    path: C:\Users\jfurtado\dart\sharepointauth
  web_ui: any
