name: bex
version: 0.3.0
author: João Furtado
description: Web UI app for SAP BW
dependencies:
  Downloadify:
    git: https://github.com/jrofurtado/Downloadify.git
  browser: any
  crypto: any
  datepicker: any
  sharepointauth:
    git: https://github.com/jrofurtado/sharepointauth.git
  web_ui: any
