name: bex
version: 0.1.0
author: João Furtado
description: Web UI app for SAP BW
dependencies:
  browser: any
  datepicker: any
  sharepointauth:
    git: https://github.com/jrofurtado/sharepointauth.git
  web_ui: any
